---
sidebar: sidebar 
permalink: about/whats-new.html 
keywords: whats new, enhancements, new features 
summary: NetApp aktualisiert regelmäßig die Automatisierungslösungen, REST-APIs und zugehörige Software, um Ihnen neue Funktionen, Verbesserungen und Bug Fixes zur Verfügung zu stellen. 
---
= Neuerungen bei NetApp-Automatisierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp aktualisiert regelmäßig die Automatisierungslösungen, REST-APIs und zugehörige Software, um Ihnen neue Funktionen, Verbesserungen und Bug Fixes zur Verfügung zu stellen.



== 27 Juli 2023

.Cloud Volumes ONTAP
Die Unterstützung von Cloud Volumes ONTAP wird durch die Public Cloud-Umgebung organisiert. Für folgende Cloud-Umgebung wird eine neue Lösung bereitgestellt:

* link:../solutions/cvo-gcp-burst-to-cloud.html["Cloud Volumes ONTAP für Google Cloud – Burst in die Cloud"]




== 04 Juni 2023

Der https://console.netapp.com/automationCatalog["NetApp Console-Automatisierungskatalog"^] ist über die Web-Benutzeroberfläche der Konsole verfügbar.  Der Automatisierungskatalog bietet Zugriff auf Lösungen, die Sie bei der automatisierten Bereitstellung und Integration von NetApp -Produkten unterstützen können.  Die Dokumentation für diese Lösungen ist in mehrere verschiedene Produkt- oder Funktionsbereiche unterteilt, wie unten beschrieben.

.Amazon FSx for NetApp ONTAP -Verwaltung
Es werden zwei Amazon FSx for NetApp ONTAP -Verwaltungslösungen wie folgt bereitgestellt:

* link:../solutions/fsxn-burst-to-cloud.html["Amazon FSx for NetApp ONTAP Management – ​​Burst to Cloud"]
* link:../solutions/fsxn-disaster-recovery.html["Amazon FSx for NetApp ONTAP Management – ​​Notfallwiederherstellung"]


.Azure NetApp Dateien
Für die Implementierung von Oracle mit Azure NetApp Files ist eine Lösung enthalten:

* link:../solutions/anf-oracle.html["Oracle mit Azure NetApp Files"]


.Cloud Volumes ONTAP
Die Unterstützung von Cloud Volumes ONTAP wird durch die Public Cloud-Umgebung organisiert. Für zwei Cloud-Umgebungen werden erste Lösungen wie folgt bereitgestellt:

* link:../solutions/cvo-aws-burst-to-cloud.html["Cloud Volumes ONTAP AWS – Burst in die Cloud"]
* link:../solutions/cvo-azure-burst-to-cloud.html["Cloud Volumes ONTAP Azure – Burst in die Cloud"]

