---
sidebar: sidebar 
permalink: api/netapp-console.html 
keywords: netapp products, product api, rest, rest api, bluexp, bluexp control plane, netapp, console 
summary: NetApp Console ist eine einheitliche Steuerungsebene, die eine hybride Multi-Cloud-Plattform für die Verwaltung von Speicher- und Datendiensten sowohl in lokalen als auch in öffentlichen Cloud-Umgebungen bereitstellt. Es besteht aus mehreren unterschiedlichen Diensten oder Komponenten, von denen jeder eine zugehörige REST-API bereitstellt.  Lesen Sie die unten angegebene Dokumentation und die zugehörigen Ressourcen, um mit der Automatisierung Ihrer Umgebung in der Konsole mithilfe der REST-APIs der Konsole zu beginnen. 
---
= NetApp Console-Steuerebene
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console ist eine einheitliche Steuerungsebene, die eine hybride Multi-Cloud-Plattform für die Verwaltung von Speicher- und Datendiensten sowohl in lokalen als auch in öffentlichen Cloud-Umgebungen bereitstellt. Es besteht aus mehreren unterschiedlichen Diensten oder Komponenten, von denen jeder eine zugehörige REST-API bereitstellt.  Lesen Sie die unten angegebene Dokumentation und die zugehörigen Ressourcen, um mit der Automatisierung Ihrer Umgebung in der Konsole mithilfe der REST-APIs der Konsole zu beginnen.

.NetApp Console REST APIs
Sie können die verschiedenen REST-APIs verwenden, um die Verwaltung Ihrer von der Konsole verwalteten Speicher- und Datendienste zu automatisieren.

* https://docs.netapp.com/us-en/console-automation/["NetApp Console API-Dokumentation"^]


.NetApp Konsolenfamilie
Die Dokumentation zur Konsolenfamilie enthält alles, was Sie für den Einstieg in die Verwendung der Konsolen-Steuerebene benötigen.

* https://docs.netapp.com/us-en/console-family/["Dokumentation zur NetApp -Konsole"^]

